"""
M5 Matplotlib & Seaborn 視覺化 — 課後作業
==========================================
情境：把分析結果做成圖表，用視覺化說故事。

資料路徑：datasets/ecommerce/orders_enriched.csv
"""

In [1]:
import matplotlib
matplotlib.use("Agg")  # 無 GUI 環境也能跑
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
def _load_data():
    """輔助函式：讀取資料"""
plt.rcParams['axes.unicode_minus'] = False
sns.set_theme(style='whitegrid')

df = pd.read_csv(
    '../datasets/ecommerce/orders_enriched.csv',
    parse_dates=['order_date'],
)
df['month'] = df['order_date'].dt.to_period('M').astype(str)
print('資料形狀:', df.shape)

資料形狀: (188, 15)

# ============================================================
# 🟢 送分題（每題 10 分，共 30 分）
# ============================================================

In [3]:
df

,order_id,customer_id,product_id,qty,order_date,amount,customer_name,region,signup_date,vip_level,product_name,category,unit_price,stock_qty,month
0,5064,2022,1026,4.0,2025-03-26,8600.0,Victor Lin,North,2023-02-27,Gold,Dumbbell 5kg,Sports,2150,51,2025-03
1,5023,2026,1021,5.0,2025-01-05,1355.0,Zoe Huang,South,2023-05-16,Platinum,Throw Pillow,Home,271,150,2025-01
2,5123,2013,1013,2.0,2025-09-11,3538.0,Mia Huang,North,2023-07-17,Platinum,Cotton T-Shirt,Clothing,1769,174,2025-09
3,5118,2005,1028,1.0,2025-05-22,1618.0,Emma Liu,West,2023-05-18,Bronze,Water Bottle,Sports,1618,186,2025-05
4,5161,2017,1019,3.0,2025-08-20,1846.0,Quinn Chen,East,2023-08-11,Silver,Coffee Mug,Home,1846,274,2025-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,5094,2026,1019,3.0,2025-02-13,5538.0,Zoe Huang,South,2023-05-16,Platinum,Coffee Mug,Home,1846,274,2025-02
184,5041,2014,1001,5.0,2025-10-03,8135.0,Nick Huang,West,2023-09-28,Gold,Wireless Mouse,Electronics,1627,12,2025-10
185,5157,2005,1026,5.0,2025-01-02,10750.0,Emma Liu,West,2023-05-18,Bronze,Dumbbell 5kg,Sports,2150,51,2025-01
186,5134,2015,1012,5.0,2025-06-03,9580.0,Olivia Huang,North,2023-12-15,Bronze,Clean Code,Books,1916,81,2025-06
187,5135,2010,1007,4.0,2025-09-05,2436.0,Jack Liu,South,2023-03-12,Platinum,Python Cookbook,Books,609,258,2025-09

In [4]:
product_order = df.groupby('category')['amount'].sum().reset_index()
product_order

      category    amount
0        Books  182244.0
1     Clothing  133841.0
2  Electronics  100235.0
3         Home   93753.0
4       Sports  176315.0

In [14]:
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
#def green_bar_category():
"""
畫出每個商品類別 (category) 的訂單數長條圖
回傳 matplotlib Figure 物件
提示：sns.countplot 或 value_counts().plot.bar()
"""
# TODO: 你的程式碼
product_order = df.groupby('category')['stock_qty'].count().reset_index()
fig = plt.figure(figsize=(8, 4)) #開空畫布
sns.countplot(data=df, x='category', palette='viridis', hue='category', legend=False)
plt.title('order count by category')



plt.show()

In [6]:
def green_hist_amount():
    """
    畫出訂單金額 (amount) 的分佈直方圖，分 20 個 bin
    回傳 matplotlib Figure 物件
    提示：sns.histplot(bins=20) 或 plt.hist()
    """
    # TODO: 你的程式碼
    pass

In [17]:
#def green_set_labels():
"""
建立一個簡單的長條圖（內容不限），但必須設定：
- 圖標題 (title)
- X 軸標籤 (xlabel)
- Y 軸標籤 (ylabel)
回傳 matplotlib Figure 物件
"""
    # TODO: 你的程式碼
region_rev = df.groupby('region')['amount'].sum().sort_values(ascending=False).reset_index()
plt.figure(figsize=(8, 4)) #開空畫布
sns.barplot(data=region_rev, x='region', y='amount', palette='viridis', hue='region', legend=False)
plt.title('Revenue by Region', fontweight='bold')
plt.xlabel('Region')
plt.ylabel('Revenue (NT$)')

# 在柱子上標數字
for i, v in enumerate(region_rev['amount']):
    plt.text(i, v, f'{v:,.0f}', ha='center', va='bottom', fontsize=10)

plt.tight_layout()
plt.show()

# ============================================================
# 🟡 核心題（每題 15 分，共 45 分）
# ============================================================

In [18]:
df

,order_id,customer_id,product_id,qty,order_date,amount,customer_name,region,signup_date,vip_level,product_name,category,unit_price,stock_qty,month
0,5064,2022,1026,4.0,2025-03-26,8600.0,Victor Lin,North,2023-02-27,Gold,Dumbbell 5kg,Sports,2150,51,2025-03
1,5023,2026,1021,5.0,2025-01-05,1355.0,Zoe Huang,South,2023-05-16,Platinum,Throw Pillow,Home,271,150,2025-01
2,5123,2013,1013,2.0,2025-09-11,3538.0,Mia Huang,North,2023-07-17,Platinum,Cotton T-Shirt,Clothing,1769,174,2025-09
3,5118,2005,1028,1.0,2025-05-22,1618.0,Emma Liu,West,2023-05-18,Bronze,Water Bottle,Sports,1618,186,2025-05
4,5161,2017,1019,3.0,2025-08-20,1846.0,Quinn Chen,East,2023-08-11,Silver,Coffee Mug,Home,1846,274,2025-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,5094,2026,1019,3.0,2025-02-13,5538.0,Zoe Huang,South,2023-05-16,Platinum,Coffee Mug,Home,1846,274,2025-02
184,5041,2014,1001,5.0,2025-10-03,8135.0,Nick Huang,West,2023-09-28,Gold,Wireless Mouse,Electronics,1627,12,2025-10
185,5157,2005,1026,5.0,2025-01-02,10750.0,Emma Liu,West,2023-05-18,Bronze,Dumbbell 5kg,Sports,2150,51,2025-01
186,5134,2015,1012,5.0,2025-06-03,9580.0,Olivia Huang,North,2023-12-15,Bronze,Clean Code,Books,1916,81,2025-06
187,5135,2010,1007,4.0,2025-09-05,2436.0,Jack Liu,South,2023-03-12,Platinum,Python Cookbook,Books,609,258,2025-09

In [27]:
def yellow_line_region_trend():
    """
    畫折線圖：比較 North 和 South 兩個地區的月營收趨勢
    - X 軸：月份
    - Y 軸：該月總營收
    - 兩條線，有圖例 (legend)
    回傳 matplotlib Figure 物件
    提示：分別 groupby 再 plot，或用 sns.lineplot(hue='region')
    """
    # TODO: 你的程式碼
target_regions = df[df['region'].isin(['North', 'South'])].copy()
target_regions['month'] = target_regions['order_date'].dt.month

region_rev = target_regions.groupby(['month','region'])['amount'].sum().reset_index()

plt.figure(figsize=(10, 5))
sns.lineplot(data=region_rev, x='month', y='amount', hue = 'region', marker='o', linewidth=2)
plt.title('Monthly region Trend', fontsize=14, fontweight='bold')
plt.xlabel('Month')
plt.ylabel('total revenue')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

In [29]:
def yellow_box_vip():
    """
    畫箱形圖：比較不同 VIP 等級 (vip_level) 的訂單金額分佈
    回傳 matplotlib Figure 物件
    提示：sns.boxplot(x='vip_level', y='amount', data=df)
    """
    # TODO: 你的程式碼
plt.figure(figsize=(9, 5))
sns.boxplot(data=df, x='vip_level', y='amount', palette='Set2', hue='vip_level', legend=False)
plt.title('Order Amount Distribution by vip level', fontweight='bold')
plt.xlabel('vip_level')
plt.ylabel('Amount')
plt.xticks(rotation=15)
plt.tight_layout()
plt.show()

In [30]:
def yellow_scatter_price_amount():
    """
    畫散佈圖：X=商品單價 (unit_price)，Y=訂單金額 (amount)
    回傳 matplotlib Figure 物件
    提示：plt.scatter() 或 sns.scatterplot()
    """
    # TODO: 你的程式碼
plt.figure(figsize=(9, 5))
sns.scatterplot(data=df, x='unit_price', y='amount',
                hue='category', alpha=0.6, s=60)
plt.title('Unit Price vs Order Amount (by Category)', fontweight='bold')
plt.xlabel('Unit Price')
plt.ylabel('Order Amount')
plt.legend(bbox_to_anchor=(1.02, 1), loc='upper left')
plt.tight_layout()
plt.show()

# ============================================================
# 🔴 挑戰題（25 分）
# ============================================================

In [34]:
def red_category_dashboard(category="Electronics"):
    """
    針對指定類別，畫 2×2 的 subplot dashboard：
    1. 左上：該類別月營收趨勢 (折線圖)
    2. 右上：該類別各地區營收 (長條圖)
    3. 左下：該類別 Top 5 商品營收 (水平長條圖)
    4. 右下：該類別訂單金額分佈 (直方圖)

    回傳 matplotlib Figure 物件
    提示：fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    """
    # TODO: 你的程式碼
fig, axes = plt.subplots(2, 2, figsize=(16, 9))
fig.suptitle('Electronics Sales Dashboard — 2025', fontsize=16, fontweight='bold')

# (0,0) 月度趨勢
electronics_df = df[df['category'].str.lower() == 'electronics']
region_electronics_rev = electronics_df.groupby('region')['amount'].sum().reset_index()
plt.figure(figsize=(8, 4)) 
sns.lineplot(data=region_electronics_rev, x='region', y='amount', marker='o', ax=axes[0, 0])
plt.title('Electronics Revenue by Region', fontweight='bold')
plt.xlabel('Region')
plt.ylabel('Revenue (NT$)')

# (0,1) 地區排名
sns.barplot(data=region_electronics_rev, x='region', y='amount', ax=axes[0, 1],
            palette='viridis', hue='region', legend=False)
axes[0, 1].set_title('electronics_Revenue by Region')

# (1,0) 品類分布

electronics_df = df[df['category'].str.lower() == 'electronics']
product_rev = electronics_df.groupby('product_name')['amount'].sum().reset_index()
top5_products = product_rev.sort_values('amount', ascending=False).head(5)
fig = plt.figure(figsize=(10, 6))
sns.barplot(
        data=top5_products, 
        x='amount',          
        y='product_name',     
        hue='product_name', 
        legend=False
    )

# (1,1) 金額散佈
sns.scatterplot(data=df, x='category', y='amount',
                hue='category', alpha=0.6, ax=axes[1, 1], legend=False)
axes[1, 1].set_title('electronics Amount')

plt.tight_layout()
plt.show()

In [33]:
df

,order_id,customer_id,product_id,qty,order_date,amount,customer_name,region,signup_date,vip_level,product_name,category,unit_price,stock_qty,month
0,5064,2022,1026,4.0,2025-03-26,8600.0,Victor Lin,North,2023-02-27,Gold,Dumbbell 5kg,Sports,2150,51,3
1,5023,2026,1021,5.0,2025-01-05,1355.0,Zoe Huang,South,2023-05-16,Platinum,Throw Pillow,Home,271,150,1
2,5123,2013,1013,2.0,2025-09-11,3538.0,Mia Huang,North,2023-07-17,Platinum,Cotton T-Shirt,Clothing,1769,174,9
3,5118,2005,1028,1.0,2025-05-22,1618.0,Emma Liu,West,2023-05-18,Bronze,Water Bottle,Sports,1618,186,5
4,5161,2017,1019,3.0,2025-08-20,1846.0,Quinn Chen,East,2023-08-11,Silver,Coffee Mug,Home,1846,274,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,5094,2026,1019,3.0,2025-02-13,5538.0,Zoe Huang,South,2023-05-16,Platinum,Coffee Mug,Home,1846,274,2
184,5041,2014,1001,5.0,2025-10-03,8135.0,Nick Huang,West,2023-09-28,Gold,Wireless Mouse,Electronics,1627,12,10
185,5157,2005,1026,5.0,2025-01-02,10750.0,Emma Liu,West,2023-05-18,Bronze,Dumbbell 5kg,Sports,2150,51,1
186,5134,2015,1012,5.0,2025-06-03,9580.0,Olivia Huang,North,2023-12-15,Bronze,Clean Code,Books,1916,81,6
187,5135,2010,1007,4.0,2025-09-05,2436.0,Jack Liu,South,2023-03-12,Platinum,Python Cookbook,Books,609,258,9